#!/bin/bash
function test {
    "$@"
    local status=$?
    if [ $status -eq -2 ]; then
        echo "TODO: Run upgrade and restart wigateway" >&2
        stop wigateway
    fi
    return $status
}

test /usr/bin/wigateway >> /var/log/wigateway