#!/bin/bash
# Author: Lance Hartung

case "$1" in
    start)
        iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
        ifconfig wlan0 up 192.168.2.1 netmask 255.255.255.0
        ifconfig eth0 up 192.168.1.1 netmask 255.255.255.0
        
        /etc/init.d/hostapd start
        /etc/init.d/dnsmasq start

        ;;
    stop)

        /etc/init.d/dnsmasq stop
        /etc/init.d/hostapd stop

        ;;
    restart)
        $0 stop
        sleep 5s
        $0 start

        ;;
    *)
        echo "Usage $0 {start|stop|restart}" >&2
        exit 1

        ;;
esac

