#!/bin/bash
# Author: Lance Hartung

case "$1" in
    start)
        iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
        ;;
    stop)

        ;;
    restart)
        $0 stop
        sleep 5s
        $0 start

        ;;
    *)
        echo "Usage $0 {start|stop|restart}" >&2
        exit 1

        ;;
esac